/* Run with Playwright available in NODE_PATH after starting the preview server. */
const { chromium } = require('playwright')
const assert = require('node:assert/strict')
const base = process.env.PORTFOLIO_TEST_URL || 'http://127.0.0.1:4175/portfolio-angel-cardenas/'

;(async () => {
  const browser = await chromium.launch({ headless: true, ignoreDefaultArgs: ['--disable-dev-shm-usage'], args: ['--no-sandbox'] })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, colorScheme: 'dark', acceptDownloads: true })
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  try {
    await page.addInitScript(() => { localStorage.setItem('language', 'es'); localStorage.setItem('theme', 'dark'); localStorage.setItem('motion-paused', 'false') })
    await page.goto(`${base}lab/`)
    await page.getByRole('heading', { name: 'TENSHI LAB' }).waitFor()
    assert.equal(await page.locator('.lab-experiment-card').count(), 2)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    await page.getByRole('button', { name: 'Switch to English' }).click()
    await page.getByText('Experimental software division.', { exact: true }).waitFor()
    assert.equal(await page.locator('html').getAttribute('lang'), 'en')
    await page.getByRole('button', { name: 'Cambiar a español' }).click()
    await page.getByRole('button', { name: 'Activar tema claro' }).click()
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'light')
    await page.getByRole('button', { name: 'Activate dark theme' }).click()

    await page.getByRole('heading', { name: 'DEBUG CHALLENGE' }).click()
    await page.waitForURL(/lab\/debug\/$/)
    await page.getByRole('heading', { name: 'Elige tu prueba.' }).waitFor()
    assert.equal(await page.locator('.challenge-card').count(), 6)
    assert.equal(await page.locator('.challenge-language-group').count(), 2)
    await page.getByRole('heading', { name: 'Python intermedio' }).waitFor()
    await page.getByRole('heading', { name: 'Python difícil' }).waitFor()
    await page.getByRole('heading', { name: 'JavaScript intermedio' }).waitFor()
    await page.getByRole('heading', { name: 'JavaScript difícil' }).waitFor()
    await page.getByRole('heading', { name: 'Python básico' }).click()
    await page.waitForURL(/lab\/debug\/python\/basic\/$/)
    await page.getByText('ÁNGEL', { exact: true }).waitFor()
    for (let index = 0; index < 4; index += 1) await page.getByRole('button', { name: /Continuar|Continue/ }).click()
    await page.getByRole('button', { name: /Transferir sesión|Transfer session/ }).click()
    await page.getByText('CHIMUELO', { exact: true }).waitFor({ timeout: 5000 })
    for (let index = 0; index < 4; index += 1) await page.getByRole('button', { name: /Continuar|Continue/ }).click()
    await page.getByRole('button', { name: 'BEGIN EXAM' }).click()
    await page.getByRole('textbox', { name: /Editor de código python|python code editor/i }).waitFor()
    assert.equal(await page.getByText('100', { exact: true }).first().textContent(), '100')

    await page.getByRole('button', { name: /RUN CODE/ }).click()
    await page.getByText('FAILED', { exact: true }).first().waitFor({ timeout: 3000 })
    assert.equal(await page.getByText('01', { exact: true }).count() > 0, true)
    await page.getByRole('button', { name: /PREGUNTAR A CHIMUELO|ASK CHIMUELO/ }).click()
    await page.getByText('-8', { exact: true }).waitFor()
    await page.getByRole('textbox', { name: /Editor de código python|python code editor/i }).fill(`usuarios = ["angel", "nicolas"]\n\ndef agregar_usuario(nombre):\n    usuarios.append(nombre)\n\nagregar_usuario("natasha")\n\nprint(usuarios)`)
    await page.getByRole('button', { name: /RUN CODE/ }).click()
    await page.getByText('DEBUG COMPLETE', { exact: true }).waitFor({ timeout: 6000 })
    await page.getByText('CHIMUELO', { exact: true }).waitFor({ timeout: 4000 })
    for (let index = 0; index < 7; index += 1) await page.getByRole('button', { name: /Continuar|Continue/ }).click()
    await page.getByRole('button', { name: /Recibir medalla|Receive medal/ }).click()
    await page.getByRole('heading', { name: /DEBUGGER/ }).waitFor()
    assert.equal(await page.getByText('92 / 100', { exact: true }).count(), 1)

    await page.getByRole('button', { name: /DESCARGAR CERTIFICADO|DOWNLOAD CERTIFICATE/ }).click()
    await page.getByRole('alert').waitFor()
    await page.getByLabel(/Nombre para la certificación|Name for certification/).fill('Test Participant')
    const certificateDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: /DESCARGAR CERTIFICADO|DOWNLOAD CERTIFICATE/ }).click()
    assert.match((await certificateDownload).suggestedFilename(), /tenshi-lab-python-debug-test-participant\.png/)
    const medalDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: /DESCARGAR MEDALLA|DOWNLOAD MEDAL/ }).click()
    assert.match((await medalDownload).suggestedFilename(), /tenshi-lab-python-gold-debugger\.png/)

    await page.getByRole('button', { name: /VOLVER A DESAFÍOS|BACK TO CHALLENGES/ }).click()
    await page.waitForURL(/\/lab\/debug\/$/)
    await page.getByRole('heading', { name: 'JavaScript básico' }).click()
    await page.waitForURL(/lab\/debug\/javascript\/basic\/$/)
    await page.getByRole('button', { name: /Omitir intro|Skip intro/ }).click()
    await page.getByText('CHIMUELO', { exact: true }).waitFor({ timeout: 5000 })
    await page.getByText(/JavaScript\. Cámara 02\./).waitFor()
    for (let index = 0; index < 4; index += 1) await page.getByRole('button', { name: /Continuar|Continue/ }).click()
    await page.getByRole('button', { name: 'BEGIN EXAM' }).click()
    const jsEditor = page.getByRole('textbox', { name: /Editor de código javascript|javascript code editor/i })
    await jsEditor.waitFor()
    await jsEditor.fill(`const price = 120;\nconst discount = 20;\n\nfunction calculateFinalPrice(price, discount) {\n  return price - discount;\n}\n\nconsole.log(calculateFinalPrice(price, discount));`)
    await page.getByRole('button', { name: /RUN CODE/ }).click()
    await page.getByText('DEBUG COMPLETE', { exact: true }).waitFor({ timeout: 6000 })
    for (let index = 0; index < 7; index += 1) await page.getByRole('button', { name: /Continuar|Continue/ }).click()
    await page.getByRole('button', { name: /Recibir medalla|Receive medal/ }).click()
    await page.getByRole('heading', { name: /GOLD DEBUGGER/ }).waitFor()
    assert.match(await page.locator('.debug-result-data div').last().textContent(), /TL-JS01-100-/)
    await page.getByRole('button', { name: /VOLVER A DESAFÍOS|BACK TO CHALLENGES/ }).click()
    await page.getByRole('button', { name: /Volver al Lab|Back to Lab/ }).click()
    await page.waitForURL(/\/lab\/$/)
    await page.getByRole('heading', { name: 'DUM' }).click()
    await page.waitForURL(/\/lab\/dum\/$/)
    await page.locator('.dom-overlay[open]').waitFor()
    await page.getByRole('button', { name: /Cerrar juego|Close game/ }).click()
    await page.waitForURL(/\/lab\/$/)

    await page.goto(base)
    await page.getByRole('button', { name: /Abrir terminal|Open interactive terminal/ }).click()
    await page.getByRole('textbox', { name: /Comando de terminal|Terminal command/ }).fill('debug')
    await page.getByRole('textbox', { name: /Comando de terminal|Terminal command/ }).press('Enter')
    await page.waitForURL(/\/lab\/debug\/$/)

    await page.setViewportSize({ width: 320, height: 800 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto(`${base}lab/debug/`)
    await page.getByRole('heading', { name: 'Elige tu prueba.' }).waitFor()
    assert.equal(await page.locator('.challenge-card').count(), 6)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Challenge selector must not overflow at 320px')
    await page.goto(`${base}lab/debug/python/basic/`)
    await page.getByText('ÁNGEL', { exact: true }).waitFor()
    assert.equal(await page.locator('.lab-preferences button').nth(2).isDisabled(), true)
    assert.equal(await page.locator('html').getAttribute('data-motion'), 'off')
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Lab must not overflow at 320px')
    assert.deepEqual(errors, [])
  } finally {
    await browser.close()
  }
})().catch((error) => { console.error(error); process.exitCode = 1 })
